export default {
  patientList: [
    {
      name: 'asfad',
      profileUrl:'https://material-ui.com/static/images/cards/paella.jpg',
      pranchageName: 'asfad',
      createdBy: 'asfad',
      createdOn: 'Saturday, 5 October 2019',
      updatedOn: 'Saturday, 5 October 2019',
      pranchageName:'asfaeaf',
      phoneNumber:'9876534567',
      email:'asfaeaf@dfda.com',
      qualification:'asfaeaf',
      treatments:'asfaeaf',
      pranchageType:'asfaeaf',
      pranchageAddress:'asfaeaf',
      littleAbout: 'By default, we use the combination of a <div> element and a background image to display the media. It can be problematic in some situations'
    },
    {
      name: 'zzzzzasfad',
      profileUrl:'https://material-ui.com/static/images/cards/paella.jpg',
      pranchageName: 'asfad',
      createdBy: 'asfad',
      createdOn: 'Saturday, 5 October 2019',
      updatedOn: 'Saturday, 5 October 2019',
      pranchageName:'asfaeaf',
      phoneNumber:'9876534567',
      email:'asfaeaf@dfda.com',
      qualification:'asfaeaf',
      treatments:'asfaeaf',
      pranchageType:'asfaeaf',
      pranchageAddress:'asfaeaf',
      littleAbout: 'By default, we use the combination of a <div> element and a background image to display the media. It can be problematic in some situations'

    },
    {
      name: 'ttttasfad',
      profileUrl:'https://material-ui.com/static/images/cards/paella.jpg',
      pranchageName: 'asfad',
      createdBy: 'asfad',
      createdOn: 'Saturday, 5 October 2019',
      updatedOn: 'Saturday, 5 October 2019',
      pranchageName:'asfaeaf',
      phoneNumber:'9876534567',
      email:'asfaeaf@dfda.com',
      qualification:'asfaeaf',
      treatments:'asfaeaf',
      pranchageType:'asfaeaf',
      pranchageAddress:'asfaeaf',
      littleAbout: 'By default, we use the combination of a <div> element and a background image to display the media. It can be problematic in some situations'
    },
    {
      name: 'wwwwasfad',
      profileUrl:'https://material-ui.com/static/images/cards/paella.jpg',
      pranchageName: 'asfad',
      createdBy: 'asfad',
      createdOn: 'Saturday, 5 October 2019',
      updatedOn: 'Saturday, 5 October 2019',
      pranchageName:'asfaeaf',
      phoneNumber:'9876534567',
      email:'asfaeaf@dfda.com',
      qualification:'asfaeaf',
      treatments:'asfaeaf',
      pranchageType:'asfaeaf',
      pranchageAddress:'asfaeaf',
      littleAbout: 'By default, we use the combination of a <div> element and a background image to display the media. It can be problematic in some situations'

    },
    {
      name: '2222asfad',
      profileUrl:'https://material-ui.com/static/images/cards/paella.jpg',
      pranchageName: 'asfad',
      createdBy: 'asfad',
      createdOn: 'Saturday, 5 October 2019',
      updatedOn: 'Saturday, 5 October 2019',
      pranchageName:'asfaeaf',
      phoneNumber:'9876534567',
      email:'asfaeaf@dfda.com',
      qualification:'asfaeaf',
      treatments:'asfaeaf',
      pranchageType:'asfaeaf',
      pranchageAddress:'asfaeaf',
      littleAbout: 'By default, we use the combination of a <div> element and a background image to display the media. It can be problematic in some situations'

    },
    {
      name: 'llasfad',
      profileUrl:'https://material-ui.com/static/images/cards/paella.jpg',
      pranchageName: 'asfad',
      createdBy: 'asfad',
      createdOn: 'Saturday, 5 October 2019',
      updatedOn: 'Saturday, 5 October 2019',
      pranchageName:'asfaeaf',
      phoneNumber:'9876534567',
      email:'asfaeaf@dfda.com',
      qualification:'asfaeaf',
      treatments:'asfaeaf',
      pranchageType:'asfaeaf',
      pranchageAddress:'asfaeaf',
      littleAbout: 'By default, we use the combination of a <div> element and a background image to display the media. It can be problematic in some situations'
    },
  ]
}
